GENRES = [
    # ── Original 12 ───────────────────────────────────────────────────────
    {"id": "rock",       "label": "Rock",       "icon": "🎸", "subgenres": ["indie rock", "alternative rock", "classic rock", "punk rock", "post-rock"]},
    {"id": "pop",        "label": "Pop",        "icon": "🎤", "subgenres": ["synth pop", "indie pop", "electropop", "dream pop", "art pop"]},
    {"id": "jazz",       "label": "Jazz",       "icon": "🎷", "subgenres": ["smooth jazz", "bebop", "cool jazz", "jazz fusion", "acid jazz"]},
    {"id": "electronic", "label": "Electronic", "icon": "🎹", "subgenres": ["ambient electronic", "house", "techno", "drum and bass", "trance"]},
    {"id": "hiphop",     "label": "Hip-Hop",    "icon": "🎙️", "subgenres": ["boom bap", "trap", "lo-fi hip hop", "conscious hip hop", "jazz rap"]},
    {"id": "classical",  "label": "Classical",  "icon": "🎻", "subgenres": ["orchestral", "chamber music", "piano solo", "romantic era", "minimalist"]},
    {"id": "lofi",       "label": "Lo-Fi",      "icon": "📻", "subgenres": ["lo-fi hip hop", "lo-fi chill", "lo-fi jazz", "lo-fi ambient", "chillhop"]},
    {"id": "ambient",    "label": "Ambient",    "icon": "🌊", "subgenres": ["dark ambient", "space ambient", "nature ambient", "drone", "new age"]},
    {"id": "rnb",        "label": "R&B",        "icon": "💜", "subgenres": ["neo soul", "contemporary R&B", "funk", "quiet storm", "alternative R&B"]},
    {"id": "folk",       "label": "Folk",       "icon": "🪕", "subgenres": ["indie folk", "acoustic folk", "folk rock", "Americana", "chamber folk"]},
    {"id": "metal",      "label": "Metal",      "icon": "🤘", "subgenres": ["progressive metal", "doom metal", "symphonic metal", "post-metal", "melodic death metal"]},
    {"id": "country",    "label": "Country",    "icon": "🤠", "subgenres": ["alt-country", "country pop", "bluegrass", "outlaw country", "country rock"]},
    # ── New 12 ────────────────────────────────────────────────────────────
    {"id": "blues",      "label": "Blues",      "icon": "🎺", "subgenres": ["delta blues", "Chicago blues", "blues rock", "electric blues", "acoustic blues"]},
    {"id": "soul",       "label": "Soul",       "icon": "✨", "subgenres": ["classic soul", "Northern soul", "psychedelic soul", "blue-eyed soul", "modern soul"]},
    {"id": "reggae",     "label": "Reggae",     "icon": "🌴", "subgenres": ["roots reggae", "dub", "dancehall", "lovers rock", "ska-reggae"]},
    {"id": "latin",      "label": "Latin",      "icon": "💃", "subgenres": ["reggaeton", "salsa", "cumbia", "bachata", "Latin pop"]},
    {"id": "afrobeats",  "label": "Afrobeats",  "icon": "🥁", "subgenres": ["Afro-pop", "Afro-fusion", "amapiano", "highlife", "Afro-house"]},
    {"id": "disco",      "label": "Disco",      "icon": "🪩", "subgenres": ["nu-disco", "Italo disco", "space disco", "boogie", "disco funk"]},
    {"id": "punk",       "label": "Punk",       "icon": "🔥", "subgenres": ["hardcore punk", "pop punk", "post-punk", "anarcho-punk", "skate punk"]},
    {"id": "soundtrack", "label": "Soundtrack",  "icon": "🎬", "subgenres": ["orchestral score", "ambient score", "electronic score", "adventure theme", "horror soundtrack"]},
    {"id": "synthwave",  "label": "Synthwave",  "icon": "🌆", "subgenres": ["retrowave", "darksynth", "outrun", "dreamwave", "vaporwave"]},
    {"id": "gospel",     "label": "Gospel",     "icon": "⛪", "subgenres": ["contemporary gospel", "traditional gospel", "gospel choir", "gospel R&B", "praise and worship"]},
    {"id": "ska",        "label": "Ska",        "icon": "🎺", "subgenres": ["two-tone ska", "ska punk", "traditional ska", "rocksteady", "third-wave ska"]},
    {"id": "bossanova",  "label": "Bossa Nova", "icon": "🌙", "subgenres": ["classic bossa nova", "modern bossa", "bossa jazz", "tropical bossa", "acoustic bossa"]},
    # ── New 12 ────────────────────────────────────────────────────────────
    {"id": "funk",       "label": "Funk",       "icon": "🕺", "subgenres": ["classic funk", "P-funk", "funk rock", "jazz funk", "neo-funk"]},
    {"id": "indie",      "label": "Indie",      "icon": "🎶", "subgenres": ["indie rock", "indie pop", "indie folk", "dream pop", "shoegaze"]},
    {"id": "house",      "label": "House",      "icon": "🏠", "subgenres": ["deep house", "tech house", "Chicago house", "progressive house", "soulful house"]},
    {"id": "techno",     "label": "Techno",     "icon": "⚡", "subgenres": ["Detroit techno", "Berlin techno", "industrial techno", "minimal techno", "acid techno"]},
    {"id": "dnb",        "label": "Drum & Bass","icon": "🥁", "subgenres": ["liquid DnB", "neurofunk", "jungle", "jump-up", "halftime"]},
    {"id": "trap",       "label": "Trap",       "icon": "🔊", "subgenres": ["Atlanta trap", "trap soul", "Latin trap", "dark trap", "trap metal"]},
    {"id": "flamenco",   "label": "Flamenco",   "icon": "💃", "subgenres": ["traditional flamenco", "flamenco fusion", "nuevo flamenco", "flamenco jazz", "flamencoPop"]},
    {"id": "newage",     "label": "New Age",    "icon": "🔮", "subgenres": ["meditative", "healing", "space music", "nature sounds", "ambient new age"]},
    {"id": "samba",      "label": "Samba",      "icon": "🎊", "subgenres": ["samba pagode", "samba enredo", "samba rock", "gafieira", "partido alto"]},
    {"id": "bluegrass",  "label": "Bluegrass",  "icon": "🪕", "subgenres": ["traditional bluegrass", "progressive bluegrass", "newgrass", "Appalachian", "mountain music"]},
    {"id": "opera",      "label": "Opera",      "icon": "🎭", "subgenres": ["Italian opera", "German opera", "baroque opera", "contemporary opera", "operetta"]},
    {"id": "celtic",     "label": "Celtic",     "icon": "☘️", "subgenres": ["Irish traditional", "Scottish folk", "Celtic rock", "Celtic fusion", "Gaelic song"]},
]

KEYWORDS = [
    # ── Emotion (merged with Energy in UI; ordered low → high energy) ────────
    {"id": "melancholic", "label": "Melancholic",  "category": "emotion"},
    {"id": "tender",      "label": "Tender",        "category": "emotion"},
    {"id": "longing",     "label": "Longing",       "category": "emotion"},
    {"id": "nostalgic",   "label": "Nostalgic",     "category": "emotion"},
    {"id": "bittersweet", "label": "Bittersweet",   "category": "emotion"},
    {"id": "whimsical",   "label": "Whimsical",     "category": "emotion"},
    {"id": "romantic",    "label": "Romantic",      "category": "emotion"},
    {"id": "hopeful",     "label": "Hopeful",       "category": "emotion"},
    {"id": "chill",       "label": "Chill",         "category": "energy"},
    {"id": "laid-back",   "label": "Laid-back",     "category": "energy"},
    {"id": "playful",     "label": "Playful",       "category": "energy"},
    {"id": "joyful",      "label": "Joyful",        "category": "emotion"},
    {"id": "hypnotic",    "label": "Hypnotic",      "category": "energy"},
    {"id": "anxious",     "label": "Anxious",       "category": "emotion"},
    {"id": "upbeat",      "label": "Upbeat",        "category": "energy"},
    {"id": "rebellious",  "label": "Rebellious",    "category": "emotion"},
    {"id": "defiant",     "label": "Defiant",       "category": "energy"},
    {"id": "energetic",   "label": "Energetic",     "category": "energy"},
    {"id": "intense",     "label": "Intense",       "category": "energy"},
    {"id": "triumphant",  "label": "Triumphant",    "category": "energy"},
    # ── Atmosphere (merged with Texture in UI; ordered low → high energy) ─
    {"id": "serene",      "label": "Serene",        "category": "atmosphere"},
    {"id": "intimate",    "label": "Intimate",      "category": "atmosphere"},
    {"id": "minimal",     "label": "Minimal",       "category": "texture"},
    {"id": "dreamy",      "label": "Dreamy",        "category": "atmosphere"},
    {"id": "warm",        "label": "Warm",          "category": "texture"},
    {"id": "ethereal",    "label": "Ethereal",      "category": "atmosphere"},
    {"id": "lush",        "label": "Lush",          "category": "texture"},
    {"id": "vast",        "label": "Vast",          "category": "atmosphere"},
    {"id": "haunting",    "label": "Haunting",      "category": "atmosphere"},
    {"id": "mysterious",  "label": "Mysterious",    "category": "atmosphere"},
    {"id": "dark",        "label": "Dark",          "category": "atmosphere"},
    {"id": "futuristic",  "label": "Futuristic",    "category": "texture"},
    {"id": "groovy",      "label": "Groovy",        "category": "texture"},
    {"id": "cinematic",   "label": "Cinematic",     "category": "atmosphere"},
    {"id": "psychedelic", "label": "Psychedelic",   "category": "texture"},
    {"id": "tense",       "label": "Tense",         "category": "atmosphere"},
    {"id": "euphoric",    "label": "Euphoric",      "category": "atmosphere"},
    {"id": "glitchy",     "label": "Glitchy",       "category": "texture"},
    {"id": "raw",         "label": "Raw",           "category": "texture"},
    {"id": "epic",        "label": "Epic",          "category": "texture"},
    # ── Instrument ────────────────────────────────────────────────────────
    {"id": "guitar",      "label": "Guitar",        "category": "instrument"},
    {"id": "bass",        "label": "Bass",          "category": "instrument"},
    {"id": "drums",       "label": "Drums",         "category": "instrument"},
    {"id": "piano",       "label": "Piano",         "category": "instrument"},
    {"id": "violin",      "label": "Violin",        "category": "instrument"},
    {"id": "saxophone",   "label": "Saxophone",     "category": "instrument"},
    {"id": "trumpet",     "label": "Trumpet",       "category": "instrument"},
    {"id": "synthesizer", "label": "Synthesizer",   "category": "instrument"},
    {"id": "cello",       "label": "Cello",         "category": "instrument"},
    {"id": "flute",       "label": "Flute",         "category": "instrument"},
    {"id": "harmonica",   "label": "Harmonica",     "category": "instrument"},
    {"id": "banjo",       "label": "Banjo",         "category": "instrument"},
    {"id": "organ",       "label": "Organ",         "category": "instrument"},
    {"id": "harp",        "label": "Harp",          "category": "instrument"},
    {"id": "mandolin",    "label": "Mandolin",      "category": "instrument"},
    {"id": "ukulele",     "label": "Ukulele",       "category": "instrument"},
    {"id": "trombone",    "label": "Trombone",      "category": "instrument"},
    {"id": "marimba",     "label": "Marimba",       "category": "instrument"},
    {"id": "sitar",       "label": "Sitar",         "category": "instrument"},
    {"id": "accordion",   "label": "Accordion",     "category": "instrument"},
]

LANGUAGES = [
    {"code": "en",           "label": "English"},
    {"code": "es",           "label": "Español"},
    {"code": "fr",           "label": "Français"},
    {"code": "de",           "label": "Deutsch"},
    {"code": "it",           "label": "Italiano"},
    {"code": "zh",           "label": "中文"},
    {"code": "el",           "label": "Ελληνικά"},
    {"code": "fi",           "label": "Suomi"},
    {"code": "sv",           "label": "Svenska"},
    {"code": "ja",           "label": "日本語"},
    {"code": "ko",           "label": "한국어"},
    {"code": "instrumental", "label": "No Vocal"},
]
