GENRES = [
    # ── Original 12 ───────────────────────────────────────────────────────
    {"id": "rock",       "label": "Rock",       "subgenres": ["indie rock", "alternative rock", "classic rock", "punk rock", "post-rock"]},
    {"id": "pop",        "label": "Pop",        "subgenres": ["synth pop", "indie pop", "electropop", "dream pop", "art pop"]},
    {"id": "jazz",       "label": "Jazz",       "subgenres": ["smooth jazz", "bebop", "cool jazz", "jazz fusion", "acid jazz"]},
    {"id": "electronic", "label": "Electronic", "subgenres": ["ambient electronic", "house", "techno", "drum and bass", "trance"]},
    {"id": "hiphop",     "label": "Hip-Hop",    "subgenres": ["boom bap", "trap", "lo-fi hip hop", "conscious hip hop", "jazz rap"]},
    {"id": "classical",  "label": "Classical",  "subgenres": ["orchestral", "chamber music", "piano solo", "romantic era", "minimalist"]},
    {"id": "lofi",       "label": "Lo-Fi",      "subgenres": ["lo-fi hip hop", "lo-fi chill", "lo-fi jazz", "lo-fi ambient", "chillhop"]},
    {"id": "ambient",    "label": "Ambient",    "subgenres": ["dark ambient", "space ambient", "nature ambient", "drone", "new age"]},
    {"id": "rnb",        "label": "R&B",        "subgenres": ["neo soul", "contemporary R&B", "funk", "quiet storm", "alternative R&B"]},
    {"id": "folk",       "label": "Folk",       "subgenres": ["indie folk", "acoustic folk", "folk rock", "Americana", "chamber folk"]},
    {"id": "metal",      "label": "Metal",      "subgenres": ["progressive metal", "doom metal", "symphonic metal", "post-metal", "melodic death metal"]},
    {"id": "country",    "label": "Country",    "subgenres": ["alt-country", "country pop", "bluegrass", "outlaw country", "country rock"]},
    # ── New 12 ────────────────────────────────────────────────────────────
    {"id": "blues",      "label": "Blues",      "subgenres": ["delta blues", "Chicago blues", "blues rock", "electric blues", "acoustic blues"]},
    {"id": "soul",       "label": "Soul",       "subgenres": ["classic soul", "Northern soul", "psychedelic soul", "blue-eyed soul", "modern soul"]},
    {"id": "reggae",     "label": "Reggae",     "subgenres": ["roots reggae", "dub", "dancehall", "lovers rock", "ska-reggae"]},
    {"id": "latin",      "label": "Latin",      "subgenres": ["reggaeton", "salsa", "cumbia", "bachata", "Latin pop"]},
    {"id": "afrobeats",  "label": "Afrobeats",  "subgenres": ["Afro-pop", "Afro-fusion", "amapiano", "highlife", "Afro-house"]},
    {"id": "disco",      "label": "Disco",      "subgenres": ["nu-disco", "Italo disco", "space disco", "boogie", "disco funk"]},
    {"id": "punk",       "label": "Punk",       "subgenres": ["hardcore punk", "pop punk", "post-punk", "anarcho-punk", "skate punk"]},
    {"id": "soundtrack", "label": "Soundtrack", "subgenres": ["orchestral score", "ambient score", "electronic score", "adventure theme", "horror soundtrack"]},
    {"id": "synthwave",  "label": "Synthwave",  "subgenres": ["retrowave", "darksynth", "outrun", "dreamwave", "vaporwave"]},
    {"id": "gospel",     "label": "Gospel",     "subgenres": ["contemporary gospel", "traditional gospel", "gospel choir", "gospel R&B", "praise and worship"]},
    {"id": "ska",        "label": "Ska",        "subgenres": ["two-tone ska", "ska punk", "traditional ska", "rocksteady", "third-wave ska"]},
    {"id": "bossanova",  "label": "Bossa Nova", "subgenres": ["classic bossa nova", "modern bossa", "bossa jazz", "tropical bossa", "acoustic bossa"]},
    # ── New 12 ────────────────────────────────────────────────────────────
    {"id": "funk",       "label": "Funk",       "subgenres": ["classic funk", "P-funk", "funk rock", "jazz funk", "neo-funk"]},
    {"id": "indie",      "label": "Indie",      "subgenres": ["indie rock", "indie pop", "indie folk", "dream pop", "shoegaze"]},
    {"id": "house",      "label": "House",      "subgenres": ["deep house", "tech house", "Chicago house", "progressive house", "soulful house"]},
    {"id": "techno",     "label": "Techno",     "subgenres": ["Detroit techno", "Berlin techno", "industrial techno", "minimal techno", "acid techno"]},
    {"id": "dnb",        "label": "Drum & Bass","subgenres": ["liquid DnB", "neurofunk", "jungle", "jump-up", "halftime"]},
    {"id": "trap",       "label": "Trap",       "subgenres": ["Atlanta trap", "trap soul", "Latin trap", "dark trap", "trap metal"]},
    {"id": "flamenco",   "label": "Flamenco",   "subgenres": ["traditional flamenco", "flamenco fusion", "nuevo flamenco", "flamenco jazz", "flamenco pop"]},
    {"id": "newage",     "label": "New Age",    "subgenres": ["meditative", "healing", "space music", "nature sounds", "ambient new age"]},
    {"id": "samba",      "label": "Samba",      "subgenres": ["samba pagode", "samba enredo", "samba rock", "gafieira", "partido alto"]},
    {"id": "bluegrass",  "label": "Bluegrass",  "subgenres": ["traditional bluegrass", "progressive bluegrass", "newgrass", "Appalachian", "mountain music"]},
    {"id": "opera",      "label": "Opera",      "subgenres": ["Italian opera", "German opera", "baroque opera", "contemporary opera", "operetta"]},
    {"id": "celtic",     "label": "Celtic",     "subgenres": ["Irish traditional", "Scottish folk", "Celtic rock", "Celtic fusion", "Gaelic song"]},
    # ── New additions ─────────────────────────────────────────────────────
    {"id": "acoustic",   "label": "Acoustic",   "subgenres": ["acoustic folk", "acoustic pop", "acoustic rock", "acoustic jazz", "acoustic blues"], "description": "No digital instruments — acoustic instruments only"},
    {"id": "swing",      "label": "Swing",      "subgenres": ["big band swing", "jump blues", "gypsy jazz", "vocal swing", "bebop swing"]},
    {"id": "grunge",     "label": "Grunge",     "subgenres": ["Seattle grunge", "post-grunge", "grunge pop", "noise rock", "sludge rock"]},
    {"id": "shoegaze",   "label": "Shoegaze",   "subgenres": ["classic shoegaze", "dream pop", "post-shoegaze", "blackgaze", "noise pop"]},
    {"id": "world",      "label": "World",      "subgenres": ["Middle Eastern", "Indian classical", "West African", "Andean", "Balkan folk"]},
    {"id": "experimental", "label": "Experimental", "subgenres": ["avant-garde", "noise", "musique concrète", "glitch", "free improvisation"]},
]

KEYWORDS = [
    # ── Emotion (merged with Energy in UI; ordered low → high energy) ────────
    {"id": "melancholic", "label": "Melancholic",  "category": "emotion"},
    {"id": "tender",      "label": "Tender",        "category": "emotion"},
    {"id": "longing",     "label": "Longing",       "category": "emotion"},
    {"id": "nostalgic",   "label": "Nostalgic",     "category": "emotion"},
    {"id": "bittersweet", "label": "Bittersweet",   "category": "emotion"},
    {"id": "whimsical",   "label": "Whimsical",     "category": "emotion"},
    {"id": "romantic",    "label": "Romantic",      "category": "emotion"},
    {"id": "hopeful",     "label": "Hopeful",       "category": "emotion"},
    {"id": "chill",       "label": "Chill",         "category": "energy"},
    {"id": "laid-back",   "label": "Laid-back",     "category": "energy"},
    {"id": "playful",     "label": "Playful",       "category": "energy"},
    {"id": "joyful",      "label": "Joyful",        "category": "emotion"},
    {"id": "hypnotic",    "label": "Hypnotic",      "category": "energy"},
    {"id": "anxious",     "label": "Anxious",       "category": "emotion"},
    {"id": "upbeat",      "label": "Upbeat",        "category": "energy"},
    {"id": "rebellious",  "label": "Rebellious",    "category": "emotion"},
    {"id": "defiant",     "label": "Defiant",       "category": "energy"},
    {"id": "energetic",   "label": "Energetic",     "category": "energy"},
    {"id": "intense",     "label": "Intense",       "category": "energy"},
    {"id": "triumphant",  "label": "Triumphant",    "category": "energy"},
    # ── Atmosphere (merged with Texture in UI; ordered low → high energy) ─
    {"id": "serene",      "label": "Serene",        "category": "atmosphere"},
    {"id": "intimate",    "label": "Intimate",      "category": "atmosphere"},
    {"id": "minimal",     "label": "Minimal",       "category": "texture"},
    {"id": "dreamy",      "label": "Dreamy",        "category": "atmosphere"},
    {"id": "warm",        "label": "Warm",          "category": "texture"},
    {"id": "ethereal",    "label": "Ethereal",      "category": "atmosphere"},
    {"id": "lush",        "label": "Lush",          "category": "texture"},
    {"id": "vast",        "label": "Vast",          "category": "atmosphere"},
    {"id": "haunting",    "label": "Haunting",      "category": "atmosphere"},
    {"id": "mysterious",  "label": "Mysterious",    "category": "atmosphere"},
    {"id": "dark",        "label": "Dark",          "category": "atmosphere"},
    {"id": "futuristic",  "label": "Futuristic",    "category": "texture"},
    {"id": "groovy",      "label": "Groovy",        "category": "texture"},
    {"id": "cinematic",   "label": "Cinematic",     "category": "atmosphere"},
    {"id": "psychedelic", "label": "Psychedelic",   "category": "texture"},
    {"id": "tense",       "label": "Tense",         "category": "atmosphere"},
    {"id": "euphoric",    "label": "Euphoric",      "category": "atmosphere"},
    {"id": "glitchy",     "label": "Glitchy",       "category": "texture"},
    {"id": "raw",         "label": "Raw",           "category": "texture"},
    {"id": "epic",        "label": "Epic",          "category": "texture"},
    # ── Decades ───────────────────────────────────────────────────────────
    {"id": "60s",         "label": "60's",          "category": "atmosphere"},
    {"id": "70s",         "label": "70's",          "category": "atmosphere"},
    {"id": "80s",         "label": "80's",          "category": "atmosphere"},
    {"id": "90s",         "label": "90's",          "category": "atmosphere"},
    {"id": "00s",         "label": "00's",          "category": "atmosphere"},
    {"id": "10s",         "label": "10's",          "category": "atmosphere"},
    {"id": "20s",         "label": "20's",          "category": "atmosphere"},
    # ── Instrument ────────────────────────────────────────────────────────
    {"id": "guitar",      "label": "Guitar",        "category": "instrument"},
    {"id": "bass",        "label": "Bass",          "category": "instrument"},
    {"id": "drums",       "label": "Drums",         "category": "instrument"},
    {"id": "piano",       "label": "Piano",         "category": "instrument"},
    {"id": "violin",      "label": "Violin",        "category": "instrument"},
    {"id": "saxophone",   "label": "Saxophone",     "category": "instrument"},
    {"id": "trumpet",     "label": "Trumpet",       "category": "instrument"},
    {"id": "synthesizer", "label": "Synthesizer",   "category": "instrument"},
    {"id": "cello",       "label": "Cello",         "category": "instrument"},
    {"id": "flute",       "label": "Flute",         "category": "instrument"},
    {"id": "harmonica",   "label": "Harmonica",     "category": "instrument"},
    {"id": "banjo",       "label": "Banjo",         "category": "instrument"},
    {"id": "organ",       "label": "Organ",         "category": "instrument"},
    {"id": "harp",        "label": "Harp",          "category": "instrument"},
    {"id": "mandolin",    "label": "Mandolin",      "category": "instrument"},
    {"id": "ukulele",     "label": "Ukulele",       "category": "instrument"},
    {"id": "trombone",    "label": "Trombone",      "category": "instrument"},
    {"id": "marimba",     "label": "Marimba",       "category": "instrument"},
    {"id": "sitar",       "label": "Sitar",         "category": "instrument"},
    {"id": "accordion",   "label": "Accordion",     "category": "instrument"},
    {"id": "oboe",        "label": "Oboe",          "category": "instrument"},
    {"id": "theremin",    "label": "Theremin",      "category": "instrument"},
    {"id": "tabla",       "label": "Tabla",         "category": "instrument"},
    {"id": "conga",       "label": "Conga",         "category": "instrument"},
    {"id": "dulcimer",    "label": "Dulcimer",      "category": "instrument"},
    {"id": "didgeridoo",  "label": "Didgeridoo",    "category": "instrument"},
]

LANGUAGES = [
    {"code": "en",           "label": "English"},
    {"code": "es",           "label": "Español"},
    {"code": "fr",           "label": "Français"},
    {"code": "de",           "label": "Deutsch"},
    {"code": "it",           "label": "Italiano"},
    {"code": "zh",           "label": "中文"},
    {"code": "el",           "label": "Ελληνικά"},
    {"code": "fi",           "label": "Suomi"},
    {"code": "sv",           "label": "Svenska"},
    {"code": "ja",           "label": "日本語"},
    {"code": "ko",           "label": "한국어"},
    {"code": "instrumental", "label": "No Vocal"},
]
